### PR TITLE
fix invalid cache length when set with zero value key

### LINKED ISSUE #17: 节点长度计算不正确
测试代码：

```go
package main

import (
	"fmt"
	"time"

	"github.com/phuslu/lru"
)

func main() {
	cache := lru.NewTTLCache[int, int](1024)
	for i := 0; i < 1000; i++ {
		cache.Set(i, i, time.Hour)
	}
	fmt.Println(cache.Len())
}
```

运行输出：

```bash
tests (main) → go run main.go
999
```

期待输出 1000.

### PR DESCRIPTION
**Pull request by godruoyi**
## Description

fix #17 

The main change is to delete the previously existing key when the list is full. Note that these changes work fine with single shard only, there still have some issues when we using multiple shards. will fix them in the next PR.

### CODE REVIEW

**Comment by phuslu** [comment]
thanks! let me look into it.

**Comment by godruoyi** [comment]
Hi @phuslu, are there any updates on this? Please feel free to ask me for more context or more updates if needed.

**Comment by phuslu** [comment]
sorry for look it lately.
1. for performance, I think it will not impact (so I'd probably to accept/merge it)
2. for correctness, I need a little time to consider it more.
Anyway, thanks again. let me complete it these two days.

File: ttl_shard.go [hunk 1]
```diff
@@ -183,7 +183,9 @@ func (s *ttlshard[K, V]) Set(hash uint32, key K, value V, ttl time.Duration) (pr
 	index := s.list[0].prev
 	node := (*ttlnode[K, V])(unsafe.Add(unsafe.Pointer(&s.list[0]), uintptr(index)*unsafe.Sizeof(s.list[0])))
 	evictedValue := node.value
-	if key != node.key {
+
+	// delete the old key if the list is full, note that the list length is size+1
+	if uint32(len(s.list)-1) < s.tableLength+1 && key != node.key {
```
Comment (ccoVeille) [inline ttl_shard.go:188]:
```suggestion
	if len(s.list)-1 < int(s.tableLength+1) && key != node.key {
```

len is an int, it can overflow int32, maybe this would be safer

**Comment by phuslu** [comment]
Seems no concerns, let's merge it first. thanks all~

**Comment by phuslu** [comment]
v1.0.17 tagged, thanks again!

**Comment by godruoyi** [comment]
this still not fixed when we using multiple shards, let's move to #25 to discuss, any suggestion on it? thanks.
